import sqlalchemy
from sqlalchemy import text

from backend.common.consts import Consts
from backend.modules.base_entities import Base
from backend.utils.udtt_utils import UdttUtils


class TradingDataDailyEntity(Base):
    __tablename__ = "tradingDataDaily"
    __table_args__ = ({"schema": Consts.APP_FIINX_DATA_EXPLORER_CORPORATE_SCHEMA},)
    __sqlServerType__ = f"[{Consts.APP_FIINX_DATA_EXPLORER_CORPORATE_SCHEMA}].[{__tablename__}]"

    __createdAt__ = sqlalchemy.Column(
        sqlalchemy.VARCHAR(20),
        nullable=False,
        server_default=text(f"FORMAT(SWITCHOFFSET(SYSUTCDATETIME(), '+07:00'), '{Consts.DATABASE_TIME_FORMAT}')"),
    )
    __updatedAt__ = sqlalchemy.Column(
        sqlalchemy.VARCHAR(20),
        nullable=False,
        server_default=text(f"FORMAT(SWITCHOFFSET(SYSUTCDATETIME(), '+07:00'), '{Consts.DATABASE_TIME_FORMAT}')"),
        default=text(f"FORMAT(SWITCHOFFSET(SYSUTCDATETIME(), '+07:00'), '{Consts.DATABASE_TIME_FORMAT}')"),
        onupdate=text(f"FORMAT(SWITCHOFFSET(SYSUTCDATETIME(), '+07:00'), '{Consts.DATABASE_TIME_FORMAT}')"),
    )
    __id__ = sqlalchemy.Column(sqlalchemy.BIGINT, primary_key=True, nullable=False, autoincrement=True)
    __hashID__ = sqlalchemy.Column(sqlalchemy.VARCHAR(32), nullable=False, unique=True)
    date = sqlalchemy.Column(sqlalchemy.VARCHAR(10))
    paramDate = sqlalchemy.Column(sqlalchemy.VARCHAR(None))
    id = sqlalchemy.Column(sqlalchemy.VARCHAR(None))
    ticker = sqlalchemy.Column(sqlalchemy.VARCHAR(None))
    # organCode = sqlalchemy.Column(sqlalchemy.VARCHAR(None), nullable=False)
    name = sqlalchemy.Column(sqlalchemy.NVARCHAR(None))
    exchangeCode = sqlalchemy.Column(sqlalchemy.VARCHAR(None))
    dataType = sqlalchemy.Column(sqlalchemy.VARCHAR(None))

    AveragePrice = sqlalchemy.Column(sqlalchemy.FLOAT)
    Beta2Y = sqlalchemy.Column(sqlalchemy.FLOAT)
    Beta6M = sqlalchemy.Column(sqlalchemy.FLOAT)
    BetaAdjust2Y = sqlalchemy.Column(sqlalchemy.FLOAT)
    BetaAdjust6M = sqlalchemy.Column(sqlalchemy.FLOAT)
    CeilingPrice = sqlalchemy.Column(sqlalchemy.FLOAT)
    ClosePrice = sqlalchemy.Column(sqlalchemy.FLOAT)
    FloorPrice = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignBuyValueDeal = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignBuyValueMatched = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignBuyValueTotal = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignBuyVolumeDeal = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignBuyVolumeMatched = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignBuyVolumeTotal = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualBuyDealValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualBuyDealVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualBuyMatchValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualBuyMatchVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualBuyValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualBuyVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualSellDealValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualSellDealVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualSellMatchValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualSellMatchVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualSellValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualSellVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignIndividualVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalBuyDealValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalBuyDealVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalBuyMatchValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalBuyMatchVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalBuyValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalBuyVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalSellDealValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalSellDealVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalSellMatchValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalSellMatchVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalSellValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalSellVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignInstitutionalVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignSellValueDeal = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignSellValueMatched = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignSellValueTotal = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignSellVolumeDeal = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignSellVolumeMatched = sqlalchemy.Column(sqlalchemy.FLOAT)
    ForeignSellVolumeTotal = sqlalchemy.Column(sqlalchemy.FLOAT)
    HighPrice = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualBuyDealValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualBuyDealVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualBuyMatchValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualBuyMatchVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualBuyValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualBuyVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualSellDealValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualSellDealVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualSellMatchValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualSellMatchVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualSellValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualSellVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalIndividualVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalBuyDealValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalBuyDealVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalBuyMatchValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalBuyMatchVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalBuyValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalBuyVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalSellDealValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalSellDealVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalSellMatchValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalSellMatchVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalSellValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalSellVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    LocalInstitutionalVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    LowPrice = sqlalchemy.Column(sqlalchemy.FLOAT)
    OpenPrice = sqlalchemy.Column(sqlalchemy.FLOAT)
    ReferencePrice = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalBidCount = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalBidVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalBuyValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalBuyVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalDealBuyValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalDealBuyVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalDealSellValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalDealSellVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalDealValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalDealVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalMatchBuyValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalMatchBuyVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalMatchSellValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalMatchSellVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalMatchValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalMatchVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalOfferCount = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalOfferVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalSellValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalSellVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalValue = sqlalchemy.Column(sqlalchemy.FLOAT)
    TotalVolume = sqlalchemy.Column(sqlalchemy.FLOAT)
    rawTicker = sqlalchemy.Column(sqlalchemy.VARCHAR(None))
    RateAdjusted = sqlalchemy.Column(sqlalchemy.FLOAT)

    @classmethod
    def generate_type(cls) -> str:
        sql_query = UdttUtils.generate_type(entity=cls)
        return sql_query
